version: '3'

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=6789
    expose:
      - "6789"
    labels:
      - traefik.backend=api
      - traefik.frontend.rule=Host:localhost
      - traefik.port=6789
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    labels:
      - "traefik.enable=false"
  rabbitmq-service:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
    labels:
      - "traefik.enable=false"