GET http://localhost:3001/users/4
Accept: */*
Cache-Control: no-cache

< user.json

###

POST http://localhost/users
Accept: */*
Cache-Control: no-cache

< user.json

###

GET http://localhost/users
###