version: '3'

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  rabbitmq-service:
    image: "rabbitmq:3-management" 
    environment: 
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672" 
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugickerns"